### ISSUE TITLE
Impossible to disable domain_expiration check after being set

### ISSUE THREAD

**Issue by justinmacleod** [BetterStackHQ/terraform-provider-better-uptime#55]
I wish to disable the domain expiration check for various monitors we have configured. Unfortunately, it appears to not be possible to disable this check via Terraform once it has been set.

I receive the `Domain expiration is invalid. Valid values are: [nil, 1, 2, 3, 7, 14, 30, 60]` error no matter what I do.

* Omitting the property results in the error.
* Changing the value to the string "nil" results in the error.
* Changing the value to the number 0 results in the error.

It appears the only way to disable the check, is to manually edit the entries in the UI and then remove the line from the TF file.

**Comment by Shadey212** [comment]
Hi there Justin,

It's Filip from Better Stack's team here jumping in. 

Thanks a lot for your message and our sincere apologies for the inconvenience. 

We've had a look into this and this seems to be caused by a discrepancy between Terraform and what we expect. We'll look into fixing this and will keep you updated on any progress. Thanks a lot for bringing this up, Justin! 🙌 

In the meantime, if you'd like to update more monitors at once, feel free to shoot us a message at "hello@betterstack.com" and we'd be happy to bulk update the monitors for you, so you could then just remove the line from the TF file. :) 

Happy to assist further with that or if anything else comes up.

Thanks a lot! 

Kind regards,
Filip

**Comment by Tatarkow** [comment]
Hello,

William from Better Stack here. I apologise once again for the troubles.

After checking the issue it seems that it is now possible to both create resources with `domain_expiration = null` and modify `domain_expiration` of existing resources to `null`. That said, I noticed a warning message regarding `null` values and legacy Terraform SDK.
![image](https://github.com/BetterStackHQ/terraform-provider-better-uptime/assets/6751346/250e6110-a284-4885-96bb-e79ed0bf8abd)

**Comment by Tatarkow** [comment]
Following my previous message, it looks like the issue has been resolved.
